# Generated by Django 5.0.1 on 2024-02-05 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_number', models.CharField(blank=True, max_length=255)),
                ('patient', models.CharField(blank=True, max_length=255)),
                ('patient_email', models.EmailField(blank=True, max_length=255)),
                ('patient_contact', models.CharField(blank=True, max_length=255)),
                ('doctor', models.CharField(blank=True, max_length=255)),
                ('doctor_email', models.EmailField(blank=True, max_length=255)),
                ('appointment_date', models.DateField(blank=True)),
                ('appointment_time', models.TimeField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('return_message', models.TextField(blank=True)),
                ('approval_status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='signed_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('contact', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('otp', models.CharField(blank=True, default='658734', max_length=10)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('credentials_sent', models.BooleanField(default=False)),
                ('is_activated_patient', models.BooleanField(default=True)),
                ('is_activated_doctor', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
