# Generated by Django 5.0.1 on 2024-02-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='role',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='role',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='signed_up',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='signed_up',
            name='updated_at',
        ),
    ]
